name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: install
        run: |
          npm install
      - name: linter
        run: |
          npm run lint
      #- name: test
      #  run: |
      #    npm run test-ci
